#ifndef RTDBDATASUB_ERRORCODE_H_INCLUDED
#define RTDBDATASUB_ERRORCODE_H_INCLUDED

#define RETURNCODE_RTDBROUTER_SUCCESS	0
#define RETURNCODE_RTDBROUTER_NOTSUBSCRIPT	-1
#define RETURNCODE_RTDBROUTER_NOTREFRESH	-2

extern const char* rtdbdatasub_strerror(int errorcode);

#endif