######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 21 10:32:41 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
CONFIG  += qt warn_on console
QT += core

INCLUDEPATH += .  $(ZMQ_ROOT)/include $(ICS_ROOT_COMP)/include
win32::LIBS += -l$(ZMQ_ROOT)/lib/libzmq-v90-mt-4_0_4
unix::LIBS += -lzmq

# Input
SOURCES += rtdbrouter_main.cpp
